### ISSUE TITLE
Can you put the PDF in to the source or host a copy online?

### ISSUE THREAD

**Issue by mw44118** [dimonomid/docker-quick-ref#2]
I want to print this out.  Don't want to build it.

**Comment by dimonomid** [comment]
The thumbnails in the readme are clickable :) Anyway, here's the same link: https://github.com/dimonomid/docker-quick-ref/releases/download/latest/docker-quick-ref.pdf

I've got the idea that the clickability might be not so obvious, so I'll update the readme.
